app/controllers/showings_controller.rb
app/models/showing.rb
config/routes.rb
frontend/src/components/showing/index.js
frontend/src/components/status-label/index.js
frontend/src/store/actions/index.js
frontend/src/store/reducer/showingsReducer.js
lib/push.rb

Add order step with push notifications

---

app/models/user.rb

Make it possible to create an account

---

frontend/src/App.js
frontend/src/store/reducers/me.js

Redirecting user to previous location upon login

---

backend/src/main/kotlin/rocks/didit/sefilm/database/entities/Movie.kt
backend/src/main/kotlin/rocks/didit/sefilm/schedulers/AsyncMovieUpdater.kt
backend/src/main/kotlin/rocks/didit/sefilm/schedulers/ScheduledPopularityUpdater.kt
backend/src/main/kotlin/rocks/didit/sefilm/web/controllers/MovieController.kt

IMDb can be N/A, this wasn't checked against.

Correctly verify IMDb id

---

frontend/src/App.js
frontend/src/Center.js
frontend/src/CopyValue.js
frontend/src/Field.js
frontend/src/Header.js
frontend/src/MainButton.js
frontend/src/Movie.js
frontend/src/PosterBox.js
frontend/src/ProjectorLoader.js
frontend/src/SelectBox.js
frontend/src/Showing.js
frontend/src/TopBar.js
frontend/src/footer/Bioord.js
frontend/src/footer/Footer.js
frontend/src/footer/QuoteBox.js
frontend/src/index.js
frontend/src/jumbotron/jumbotron.js
frontend/src/lib/withLoader.js
frontend/src/routes/Home.js
frontend/src/routes/Login.js
frontend/src/routes/NewShowing.js
frontend/src/routes/Showings.js
frontend/src/routes/SingleShowing/AdminAction.js
frontend/src/routes/SingleShowing/PendingShowing.js
frontend/src/routes/User.js

Various styling changes to make it prettier for desktop

---

frontend/src/routes/NewShowing.js

Like this! http://fontawesome.io/examples/#animated

Spin refresh button on loading

---

frontend/package.json
frontend/src/App.js
frontend/src/Showing.js
frontend/src/routes/Home.js
frontend/src/routes/NewShowing.js
frontend/src/routes/Showings.js
frontend/src/routes/SingleShowing/index.js
frontend/src/routes/User.js
frontend/yarn.lock

Set title tag for routes

---

frontend/src/routes/Login.js

Login box is once again centered:
Made background fade out into black:

Login screen styling

---

frontend/src/routes/SingleShowing/AdminAction.js
frontend/src/store/reducers/showings.js

No more hacky-hacky `setTimeout` 🎉  💃

Return promise from action so view can use result

---

frontend/coverageconfig.json
frontend/src/store/reducers/rest.js
frontend/src/store/reducers/rest.test.js
frontend/src/store/reducers/user.test.js

Add test for rest reducer, prepare for refactoring

More testing

---

backend/src/main/kotlin/rocks/didit/sefilm/clients/GoogleCalenderClient.kt
backend/src/main/kotlin/rocks/didit/sefilm/database/entities/Showing.kt
backend/src/main/kotlin/rocks/didit/sefilm/domain/dto/CalendarEventDTO.kt
backend/src/main/kotlin/rocks/didit/sefilm/web/controllers/ShowingController.kt
frontend/src/routes/SingleShowing/AdminAction.js

Also save the event ID for future use. Also hide the create calendar
button if an event has already been created

Use Stockholm/Europe as time zone

---

backend/src/main/kotlin/rocks/didit/sefilm/Exceptions.kt
backend/src/main/kotlin/rocks/didit/sefilm/web/controllers/ShowingController.kt
backend/src/main/kotlin/rocks/didit/sefilm/web/controllers/UserController.kt

When creating a new showing or updating an existing showing

Admin must have a phone number

---

frontend/src/MainButton.js
frontend/src/routes/SingleShowing/AdminAction.js
frontend/src/routes/SingleShowing/BoughtShowing.js
frontend/src/routes/SingleShowing/BuyModal.js
frontend/src/routes/SingleShowing/ParticipantsList.js
frontend/src/routes/SingleShowing/PendingShowing.js
frontend/src/routes/SingleShowing/QRCode.js
frontend/src/routes/SingleShowing/SwishModal.js
frontend/src/routes/SingleShowing/UserItem.js
frontend/src/routes/SingleShowing/index.js

Most notably a user card when viewing participants.
Looks kina like this now:

Various UI fixes

---

frontend/src/CopyValue.js

Strikethrough bioklubbnummer on copy

---

backend/src/main/kotlin/rocks/didit/sefilm/clients/GoogleCalenderClient.kt
backend/src/main/kotlin/rocks/didit/sefilm/domain/Error.kt
backend/src/main/kotlin/rocks/didit/sefilm/web/controllers/ShowingController.kt
frontend/src/routes/SingleShowing/AdminAction.js

The backend required a useless POST body for some reason

Fix adding calendar events. Fixes #131

---

frontend/src/lib/dateTools.js

Solves date formatting in all places where datepickers are used

Import sv locale

---

frontend/src/routes/SingleShowing/BuyModal.js

Show member name as tooltip for membershipid-number

---

frontend/src/routes/SingleShowing/PendingShowing.js

Do not open modal when only swish is available

---

frontend/src/IMDbLink.js
frontend/src/routes/SingleShowing/index.js

Show IMDb link on showing

---

frontend/src/fragments/movies.js
frontend/src/routes/NewShowing.js

Refetch NewShowing query when movies has been updated

---

frontend/src/footer/Footer.js

Open GitHub link in new tab

---

frontend/public/index.html
frontend/src/App.js
frontend/src/CreateShowingForm.js
frontend/src/EditShowingForm.js
frontend/src/Showing.js
frontend/src/ShowingNeue.js
frontend/src/UUIDToWebId.js
frontend/src/fragments/showings.js
frontend/src/fragments/tickets.js
frontend/src/navigators/index.js
frontend/src/routes/EditShowing.js
frontend/src/routes/Home.js
frontend/src/routes/NewShowing.js
frontend/src/routes/ShowingTickets/TicketContainer.js
frontend/src/routes/ShowingTickets/index.js
frontend/src/routes/Showings.js
frontend/src/routes/SingleShowing/AdminAction.js
frontend/src/routes/SingleShowing/BuyModal.js
frontend/src/routes/SingleShowing/createPaymentOptions.js
frontend/src/routes/SingleShowing/index.js
frontend/src/routes/User/ForetagsbiljettList.js
frontend/src/routes/User/index.js

Short urls in frontend and other stuff

---

frontend/src/use-cases/single-showing/BuyModal.js

Show membership number and ftg tickets in table

---

backend/src/main/kotlin/rocks/didit/sefilm/domain/dto/SfDTOs.kt
backend/src/main/kotlin/rocks/didit/sefilm/services/external/SFService.kt

Allow nullable posterUrl

---

Makefile
frontend/Dockerfile

Add /gitinfo path to frontend

---

frontend/src/use-cases/common/hooks/useFadeState.tsx
frontend/src/use-cases/showing-tickets/SeatRange.tsx
frontend/src/use-cases/single-showing/AdminAction.tsx
frontend/src/use-cases/single-showing/CopyHighlightStringButton.tsx

Add copy highlight string button to admin page

---

frontend/src/use-cases/single-showing/BuyModal.tsx

Resolves #300 
(yellow is hover color)

Use alternating colors and max width

---

frontend/src/use-cases/showing-tickets/Ticket.tsx
frontend/src/use-cases/showing-tickets/__snapshots__/TicketContainer.test.js.snap

Add contrast filter to aztec code img

---

backend/build.gradle.kts
backend/src/main/kotlin/rocks/didit/sefilm/Application.kt
backend/src/main/kotlin/rocks/didit/sefilm/graphql/CustomScalars.kt
backend/src/main/kotlin/rocks/didit/sefilm/graphql/GraphqlExceptionHandler.kt

Switch to non-deprecated way of creating custom scalars

Upgrade graphql to the latest version

---

backend/build.gradle.kts
backend/src/main/kotlin/rocks/didit/sefilm/SecurityConfiguration.kt
backend/src/main/resources/application.yml

Add /info and /health

---

backend/src/main/kotlin/rocks/didit/sefilm/services/CalendarService.kt

User newer URL variant in Calendar feed

---

.circleci/config.yml
Makefile
backend/src/main/kotlin/rocks/didit/sefilm/Properties.kt
backend/src/main/kotlin/rocks/didit/sefilm/services/CalendarService.kt
backend/src/main/resources/application.yml

Note this probably only works in some calendar apps. Probably won't work
in Google Calendar for example
Fixes #214

Alert 1h before showing

---

frontend/src/apollo/mutations/user.ts
frontend/src/index.tsx
frontend/src/store/apollo.js
frontend/src/use-cases/common/utils/StatusMessageBox.tsx
frontend/src/use-cases/edit-showing/EditShowing.tsx
frontend/src/use-cases/single-showing/containers/SingleShowingContainer.tsx
frontend/src/use-cases/single-showing/utils/__tests__/createPaymentOptions.test.ts
frontend/src/use-cases/single-showing/utils/createPaymentOptions.ts
frontend/src/use-cases/user/EditableForetagsbiljettList.tsx
frontend/src/use-cases/user/Foretagsbiljett.tsx
frontend/src/use-cases/user/ProfileView.tsx

Fixes #351 
Fixes #352 
Fixes #241

Correct ftg tickets mutations and show better error messages

---

.github/dependabot.yml

chore: tell dependabot to use conventional commits

---

.github/workflows/golang.yml
.github/workflows/nodejs.yml
README.md

_Now with faster CI/CD flows ™_

feat: use self-hosted action runner

---

web/yarn.lock

This reverts commit 1c5488dc1fd3095a1c3e175e12175862eef4d0cf.

revert: "chore: yarn upgrade"

---

cmd/filmstund/main.go
internal/fileserver/fileserver.go
internal/server/server.go

Makes for a more modular approach down the line.
Manually

refactor: split the server doing the listening and the server doing the heavy lifting

---

.golangci.yaml
cmd/filmstund/main.go
go.mod
go.sum
internal/fileserver/fileserver.go
internal/setup/setup.go

Now we can configure the server with environment variables
Manual

feat: allow for environment var config

---

go.mod
go.sum
internal/database/config_test.go
internal/database/connections_test.go

* Switch to a more convenient assertion library
* Add a unit test for db connections
Unit tests.

refactor: switch assertion library

---

go.mod
go.sum
internal/cinema/cinemaserver.go
internal/middleware/authentication.go
internal/middleware/authorization.go
internal/middleware/recover.go
internal/security/config.go
internal/setup/setup.go

Built to work with auth0, but should theoretically work with any provider.
Not really screenshottable...

feat(security): add JWT authorization

---

README.md

Update readme to mention podman (docker alternative)

docs(readme): add note about podman

---

api/graphql/v2/login.graphqls
api/graphql/v2/scalars.graphqls
api/graphql/v2/users.graphqls
internal/graph/gql/runtime.go
internal/graph/login.resolvers.go

This is responsible for creating or updating the user upon login.
This call is intended to be called immediately after login.

feat(login): add mutation for login

---

internal/cinema/cinemaserver.go
web/src/lib/withBaseURL.ts

Also changes the graphql url to /api/graphql

fix(backend): allow access to static files

---

internal/cinema/cinemaserver.go
internal/middleware/authorization.go
internal/serverenv/serverenv.go
internal/setup/setup.go

This should've probably been done earlier, but it was forgotten.

refactor: idTokenCache -> principalCache

---

.golangci.yaml
CONFIG.md
Makefile
configs/database/queries/users.sql
configs/gqlgen.yml
internal/cinema/calendar_feed.go
internal/cinema/cinemaserver.go
internal/cinema/config.go
internal/database/connections.go
internal/database/sqlc/users.sql.go
internal/graph/commandments.resolvers.go
internal/graph/gql/runtime.go
internal/graph/login.resolvers.go
internal/graph/mappers/user.go
internal/graph/mappers/utils.go
internal/graph/mappers/utils_test.go
internal/graph/model/models_gen.go
internal/graph/resolver.go
internal/graph/scalars/uuid.go
internal/graph/users.resolvers.go
internal/middleware/authorization.go
internal/site/config.go

Allows the user to disable and re-generate the calendar feed.

feat: resolve calendar feed mutations

---

internal/middleware/cors.go

chore(cors): disable debugging

---

internal/auth0/userinfo.go
internal/database/connections.go
internal/graph/common_errors.go
internal/graph/login.resolvers.go

The closure method used previously is nice as long as you don't need to actually return a value. This method is more suited for when values are returned.
There is also less duplication around errors.

 refactor(db): a nicer way of getting a query interface

---

tools/gofumpt/rules.mk
tools/golangci-lint/rules.mk

Add arm64 support for gofumpt & golangci

---

tools/sqlc/rules.mk

this allows it to run on any platform that you can compile it on.

fix(tools): go install sqlc

---

configs/database/migrations/000005_create_gift_certificate.down.sql
configs/database/migrations/000005_create_gift_certificate.up.sql
configs/database/queries/users.sql
internal/database/sqlc/models.go
internal/database/sqlc/users.sql.go
internal/graph/mappers/user.go
internal/graph/users.resolvers.go

The status is currently hard-coded to unknown right now. It needs to be calculated from a bunch of other data that we don't have right now.

feat(giftcerts): implement add/remove mutations

---

internal/graph/users.go
internal/graph/users.resolvers.go

refactor(users): extract fetch user func helper

---

configs/database/migrations/000006_create_movies.down.sql
configs/database/migrations/000006_create_movies.up.sql
configs/database/migrations/000007_create_showing_tables.down.sql
configs/database/migrations/000007_create_showing_tables.up.sql
internal/database/sqlc/models.go

this is more or less a direct copy of the old Filmstund application and might therefore require some minor changes here and there. But that will have to be updated in another commit.

chore(db): add movies and showing DB tables

---

api/graphql/v2/scalars.graphqls
api/graphql/v2/users.graphqls
configs/database/migrations/000002_create_commandment_table.up.sql
configs/database/migrations/000003_create_users.up.sql
configs/database/migrations/000004_create_gift_certificate.up.sql
configs/database/migrations/000005_create_movies.up.sql
configs/database/migrations/000006_create_showing_tables.up.sql
configs/database/queries/users.sql
internal/database/dao/models.go
internal/database/dao/users.sql.go
internal/graph/gql/runtime.go
internal/graph/mappers/user.go
internal/graph/model/models_gen.go
internal/graph/users.resolvers.go

refactor: rename date -> time

---

.github/workflows/frontend.yml
web/package.json
web/yarn.lock

- chore: bump node to v 16
- chore: replace emotion/core with emotion/react

chore: upgrade to node 16

---

filmstaden/get_movies.go
internal/database/connections.go
internal/graph/movie.resolvers.go

note you must call commit or rollback or you will leave the TX open
as well as the connection. You won't be able to even close the app
then...

feat(db): support database transactions

---

configs/database/queries/movies.sql
filmstaden/get_movies.go
filmstaden/get_movies_test.go
internal/database/dao/movies.sql.go
internal/graph/movie.resolvers.go

Also use the re-relase date as the release date if it exists.

refactor(movies): sort by release date

---

web/schema.graphql
web/src/__generated__/types.ts

since we updated the movie definition previously...

chore(web): update gql typings

---

api/graphql/v2/movie.graphqls
internal/graph/gql/runtime.go
internal/graph/movie.resolvers.go
web/schema.graphql
web/src/__generated__/types.ts

it defaults to GB so shouldn't break anything existing...

feat(movies): support city alias when fetching

---

api/graphql/movies.graphqls
cmd/popularity/main.go
cmd/popularity/updater.go
configs/database/migrations/000005_create_movies.up.sql
configs/database/migrations/000006_create_showing_tables.down.sql
configs/database/queries/movies.sql
go.mod
go.sum
internal/database/dao/models.go
internal/database/dao/movies.sql.go
internal/graph/gql/runtime.go
internal/graph/model/models_gen.go
internal/graph/movies.resolvers.go
web/schema.graphql
web/src/__generated__/types.ts
web/src/apollo/queries/movies.ts
web/src/use-cases/new-showing/NewShowing.tsx

This application is build as a standalone and should run in the background. 
For this PR to be possible, another repo was created: [themoviedb-go](https://github.com/Filmstund/themoviedb-go)

feat: add a movie popularity updater application

---

internal/graph/scalars/filmstadenmembershipid.go
internal/graph/scalars/filmstadenmembershipid_test.go

Must be in the format of XYZ-ABC to be considered valid.

chore(fsid): implement ID format validation

---

api/graphql/filmstaden.graphqls
cmd/popularity/updater.go
configs/database/queries/movies.sql
filmstaden/client.go
filmstaden/get_shows.go
filmstaden/get_shows_test.go
internal/database/dao/movies.sql.go
internal/graph/gql/runtime.go
internal/graph/model/models_gen.go
internal/graph/movies.resolvers.go
web/schema.graphql
web/src/__generated__/introspection.json
web/src/__generated__/types.ts
web/src/store/urql.ts
web/src/use-cases/common/showing/FilmstadenShowingSelector.tsx
web/src/use-cases/common/ui/SelectBox.tsx
web/src/use-cases/edit-showing/EditShowingForm.tsx
web/src/use-cases/new-showing/CreateShowingForm.tsx
web/src/use-cases/new-showing/filmstadenShowingsQuery.graphql

_note_ frontend hasn't been fixed yet...

feat: add GQL resolver for quering Filmstaden showings

---

web/src/use-cases/common/showing/Showing.tsx
web/src/use-cases/my-showings/Home.tsx
web/src/use-cases/showings-list/Showings.tsx
web/src/use-cases/single-showing/containers/SingleShowingContainer.tsx

fix: format showing dates

---

web/src/use-cases/new-showing/CreateShowingForm.tsx

feat: set default showing time to 19:00

---

web/src/use-cases/common/ui/SelectBox.tsx

fix: format showing time as hh:mm

---

configs/database/queries/attendees.sql
internal/cinema/cinemaserver.go
internal/currency/sek.go
internal/currency/sek_test.go
internal/database/dao/attendees.sql.go
internal/graph/payment.resolvers.go
swish/uri.go
swish/uri_test.go

feat: resolve payment details

---

.github/workflows/deploy-beta.yml
Makefile
cmd/filmstund/main.go
cmd/migrate/main.go
cmd/popularity/main.go
configs/database/migrations/embed.go

also added some improvements to the migration script to allow for easier deploy.

feat(ci): deploy to beta server on push to master

---

.github/workflows/deploy-beta-backend.yml
.github/workflows/deploy-beta-frontend.yml
.github/workflows/deploy-beta.yml

fix(ci): allow frontend to build

---

.github/workflows/deploy-beta-backend.yml
.github/workflows/deploy-beta-frontend.yml

so that we get access to the correct secrets

fix(ci): reference preprod environment

---

.github/workflows/deploy-beta-backend.yml
.github/workflows/deploy-beta-frontend.yml

and some name changes to make the workflow a bit more distinct

fix(ci): include secrets for replace job

---

.github/workflows/deploy-beta-frontend.yml

fix(ci): add `--force` flag when replacing frontend

---

.github/workflows/deploy-beta-backend.yml
.github/workflows/deploy-beta-frontend.yml

feat(ci): add deployment url to the frontend

---

.github/workflows/deploy-beta.yml

chore(ci): add specific node version on deploy

---

README.md
web/src/__generated__/types.ts
web/src/store/urql.ts
web/src/use-cases/common/showing/movieFragment.graphql
web/src/use-cases/new-showing/MovieSelector.tsx

fix: update cache after mutation

---

internal/graph/movies.resolvers.go

fix(movies): return all movies when fetching new ones

---

web/src/use-cases/new-showing/MovieSelector.tsx

lint: remove unused variable

---

api/graphql/payment.graphqls
internal/graph/gql/runtime.go
internal/graph/model/models_gen.go
internal/graph/payment.helpers.go
internal/graph/payment.helpers_test.go
internal/graph/payment.resolvers.go
web/schema.graphql
web/src/__generated__/introspection.json
web/src/__generated__/types.ts

makes it easier to cache and handle in the frontend.

fix(attendee): add ID field

---

README.md

docs(readme): update CI badges

---

configs/database/queries/tickets.sql
internal/database/dao/tickets.sql.go
internal/graph/ticket.helpers.go
internal/graph/ticket.resolvers.go

feat(tickets): implement ticket range resolver

---

.github/workflows/ci.yml
Makefile
web/Makefile

i.e. don't spread out yarn lint in three different places. Now there
is a single source of truth.

refactor(makefile): homogenize Makefiles

---

internal/graph/payment.resolvers.go

fix(payment): return nil when there are no attendees

---

internal/graph/payment.resolvers.go

i.e. we have a FS showing stored. Otherwise we link to the movie.
Closes #312

fix(filmstaden): link directly to showing if we can

---

web/src/use-cases/common/ui/LocationSelect.tsx

fix: use new option.value instead of the old value

---

configs/database/queries/tickets.sql
internal/database/dao/tickets.sql.go
internal/graph/ticket.helpers.go

also actually save the row and number of a ticket...

fix(tickets): more robust ticket assignment

---

web/package.json
web/yarn.lock

chore: remove auth0 dependency

---

.github/workflows/ci.yml
web/Makefile
web/package.json
web/yarn.lock

chore(ci): add bundlesize tracking plugin

---

web/package.json
web/vite.config.ts
web/yarn.lock

chore(web): use new react vite plugin

---

README.md
docker-compose.yml

chore: add docker-compose file for postgres & redis

---

web/src/use-cases/single-showing/containers/SingleShowingContainer.tsx

fix: fetch with cache-and-network, resolves #671

---

web/package.json
web/yarn.lock

chore: bump vite version

---

.github/dependabot.yml

ci(dependabot): ignore web patch versions
